//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.8.3928.0.
// 
namespace PhotoStudio.Models {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class photo_tech_store {
        
        private photo_tech_storeCamera[] photo_camerasField;
        
        private photo_tech_storeLens[] photo_lensesField;
        
        private photo_tech_storeFlash[] photo_flashesField;
        
        private photo_tech_storeFilter[] photo_filtersField;
        
        private photo_tech_storeTripod[] photo_tripodsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("camera", IsNullable=false)]
        public photo_tech_storeCamera[] photo_cameras {
            get {
                return this.photo_camerasField;
            }
            set {
                this.photo_camerasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("lens", IsNullable=false)]
        public photo_tech_storeLens[] photo_lenses {
            get {
                return this.photo_lensesField;
            }
            set {
                this.photo_lensesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("flash", IsNullable=false)]
        public photo_tech_storeFlash[] photo_flashes {
            get {
                return this.photo_flashesField;
            }
            set {
                this.photo_flashesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("filter", IsNullable=false)]
        public photo_tech_storeFilter[] photo_filters {
            get {
                return this.photo_filtersField;
            }
            set {
                this.photo_filtersField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("tripod", IsNullable=false)]
        public photo_tech_storeTripod[] photo_tripods {
            get {
                return this.photo_tripodsField;
            }
            set {
                this.photo_tripodsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeCamera {
        
        private photo_tech_storeCameraCamera_name camera_nameField;
        
        private string camera_imageField;
        
        private string camera_typeField;
        
        private string camera_colorField;
        
        private photo_tech_storeCameraCamera_lens camera_lensField;
        
        private float camera_megapixelsField;
        
        private bool camera_megapixelsFieldSpecified;
        
        private string camera_manifacturerField;
        
        private photo_tech_storeCameraCamera_papertype camera_papertypeField;
        
        private photo_tech_storeCameraCamera_video camera_videoField;
        
        private string camera_processorField;
        
        private photo_tech_storeCameraCamera_price camera_priceField;
        
        /// <remarks/>
        public photo_tech_storeCameraCamera_name camera_name {
            get {
                return this.camera_nameField;
            }
            set {
                this.camera_nameField = value;
            }
        }
        
        /// <remarks/>
        public string camera_image {
            get {
                return this.camera_imageField;
            }
            set {
                this.camera_imageField = value;
            }
        }
        
        /// <remarks/>
        public string camera_type {
            get {
                return this.camera_typeField;
            }
            set {
                this.camera_typeField = value;
            }
        }
        
        /// <remarks/>
        public string camera_color {
            get {
                return this.camera_colorField;
            }
            set {
                this.camera_colorField = value;
            }
        }
        
        /// <remarks/>
        public photo_tech_storeCameraCamera_lens camera_lens {
            get {
                return this.camera_lensField;
            }
            set {
                this.camera_lensField = value;
            }
        }
        
        /// <remarks/>
        public float camera_megapixels {
            get {
                return this.camera_megapixelsField;
            }
            set {
                this.camera_megapixelsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool camera_megapixelsSpecified {
            get {
                return this.camera_megapixelsFieldSpecified;
            }
            set {
                this.camera_megapixelsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public string camera_manifacturer {
            get {
                return this.camera_manifacturerField;
            }
            set {
                this.camera_manifacturerField = value;
            }
        }
        
        /// <remarks/>
        public photo_tech_storeCameraCamera_papertype camera_papertype {
            get {
                return this.camera_papertypeField;
            }
            set {
                this.camera_papertypeField = value;
            }
        }
        
        /// <remarks/>
        public photo_tech_storeCameraCamera_video camera_video {
            get {
                return this.camera_videoField;
            }
            set {
                this.camera_videoField = value;
            }
        }
        
        /// <remarks/>
        public string camera_processor {
            get {
                return this.camera_processorField;
            }
            set {
                this.camera_processorField = value;
            }
        }
        
        /// <remarks/>
        public photo_tech_storeCameraCamera_price camera_price {
            get {
                return this.camera_priceField;
            }
            set {
                this.camera_priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeCameraCamera_name {
        
        private string shutterspeedField;
        
        private float displayField;
        
        private bool displayFieldSpecified;
        
        private string isoField;
        
        private string focus_pointsField;
        
        private string storageField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string shutterspeed {
            get {
                return this.shutterspeedField;
            }
            set {
                this.shutterspeedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public float display {
            get {
                return this.displayField;
            }
            set {
                this.displayField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool displaySpecified {
            get {
                return this.displayFieldSpecified;
            }
            set {
                this.displayFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string iso {
            get {
                return this.isoField;
            }
            set {
                this.isoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string focus_points {
            get {
                return this.focus_pointsField;
            }
            set {
                this.focus_pointsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string storage {
            get {
                return this.storageField;
            }
            set {
                this.storageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeCameraCamera_lens {
        
        private string lenstypeField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string lenstype {
            get {
                return this.lenstypeField;
            }
            set {
                this.lenstypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeCameraCamera_papertype {
        
        private string paperlengthField;
        
        private string paperwidthField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string paperlength {
            get {
                return this.paperlengthField;
            }
            set {
                this.paperlengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="positiveInteger")]
        public string paperwidth {
            get {
                return this.paperwidthField;
            }
            set {
                this.paperwidthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeCameraCamera_video {
        
        private string videotypeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string videotype {
            get {
                return this.videotypeField;
            }
            set {
                this.videotypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeCameraCamera_price {
        
        private string currencyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeLens {
        
        private photo_tech_storeLensLens_name lens_nameField;
        
        private string lens_imageField;
        
        private string lens_typeField;
        
        private string lens_appertureField;
        
        private string lens_manifacturerField;
        
        private string lens_focus_rangeField;
        
        private photo_tech_storeLensLens_price lens_priceField;
        
        /// <remarks/>
        public photo_tech_storeLensLens_name lens_name {
            get {
                return this.lens_nameField;
            }
            set {
                this.lens_nameField = value;
            }
        }
        
        /// <remarks/>
        public string lens_image {
            get {
                return this.lens_imageField;
            }
            set {
                this.lens_imageField = value;
            }
        }
        
        /// <remarks/>
        public string lens_type {
            get {
                return this.lens_typeField;
            }
            set {
                this.lens_typeField = value;
            }
        }
        
        /// <remarks/>
        public string lens_apperture {
            get {
                return this.lens_appertureField;
            }
            set {
                this.lens_appertureField = value;
            }
        }
        
        /// <remarks/>
        public string lens_manifacturer {
            get {
                return this.lens_manifacturerField;
            }
            set {
                this.lens_manifacturerField = value;
            }
        }
        
        /// <remarks/>
        public string lens_focus_range {
            get {
                return this.lens_focus_rangeField;
            }
            set {
                this.lens_focus_rangeField = value;
            }
        }
        
        /// <remarks/>
        public photo_tech_storeLensLens_price lens_price {
            get {
                return this.lens_priceField;
            }
            set {
                this.lens_priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeLensLens_name {
        
        private sbyte lens_angleField;
        
        private bool lens_angleFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public sbyte lens_angle {
            get {
                return this.lens_angleField;
            }
            set {
                this.lens_angleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool lens_angleSpecified {
            get {
                return this.lens_angleFieldSpecified;
            }
            set {
                this.lens_angleFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeLensLens_price {
        
        private string currencyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeFlash {
        
        private photo_tech_storeFlashFlash_name flash_nameField;
        
        private string flash_imageField;
        
        private string flash_remoteField;
        
        private string flash_manifacturerField;
        
        private string flash_main_numberField;
        
        private photo_tech_storeFlashFlash_price flash_priceField;
        
        /// <remarks/>
        public photo_tech_storeFlashFlash_name flash_name {
            get {
                return this.flash_nameField;
            }
            set {
                this.flash_nameField = value;
            }
        }
        
        /// <remarks/>
        public string flash_image {
            get {
                return this.flash_imageField;
            }
            set {
                this.flash_imageField = value;
            }
        }
        
        /// <remarks/>
        public string flash_remote {
            get {
                return this.flash_remoteField;
            }
            set {
                this.flash_remoteField = value;
            }
        }
        
        /// <remarks/>
        public string flash_manifacturer {
            get {
                return this.flash_manifacturerField;
            }
            set {
                this.flash_manifacturerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="positiveInteger")]
        public string flash_main_number {
            get {
                return this.flash_main_numberField;
            }
            set {
                this.flash_main_numberField = value;
            }
        }
        
        /// <remarks/>
        public photo_tech_storeFlashFlash_price flash_price {
            get {
                return this.flash_priceField;
            }
            set {
                this.flash_priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeFlashFlash_name {
        
        private string flash_battery_typeField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string flash_battery_type {
            get {
                return this.flash_battery_typeField;
            }
            set {
                this.flash_battery_typeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeFlashFlash_price {
        
        private string currencyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeFilter {
        
        private string filter_nameField;
        
        private string filter_imageField;
        
        private string filter_typeField;
        
        private string filter_descriptionField;
        
        private string filter_manifacturerField;
        
        private photo_tech_storeFilterFilter_price filter_priceField;
        
        /// <remarks/>
        public string filter_name {
            get {
                return this.filter_nameField;
            }
            set {
                this.filter_nameField = value;
            }
        }
        
        /// <remarks/>
        public string filter_image {
            get {
                return this.filter_imageField;
            }
            set {
                this.filter_imageField = value;
            }
        }
        
        /// <remarks/>
        public string filter_type {
            get {
                return this.filter_typeField;
            }
            set {
                this.filter_typeField = value;
            }
        }
        
        /// <remarks/>
        public string filter_description {
            get {
                return this.filter_descriptionField;
            }
            set {
                this.filter_descriptionField = value;
            }
        }
        
        /// <remarks/>
        public string filter_manifacturer {
            get {
                return this.filter_manifacturerField;
            }
            set {
                this.filter_manifacturerField = value;
            }
        }
        
        /// <remarks/>
        public photo_tech_storeFilterFilter_price filter_price {
            get {
                return this.filter_priceField;
            }
            set {
                this.filter_priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeFilterFilter_price {
        
        private string currencyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeTripod {
        
        private string tripod_nameField;
        
        private string tripod_imageField;
        
        private float tripod_heightField;
        
        private string tripod_manifacturerField;
        
        private photo_tech_storeTripodTripod_price tripod_priceField;
        
        /// <remarks/>
        public string tripod_name {
            get {
                return this.tripod_nameField;
            }
            set {
                this.tripod_nameField = value;
            }
        }
        
        /// <remarks/>
        public string tripod_image {
            get {
                return this.tripod_imageField;
            }
            set {
                this.tripod_imageField = value;
            }
        }
        
        /// <remarks/>
        public float tripod_height {
            get {
                return this.tripod_heightField;
            }
            set {
                this.tripod_heightField = value;
            }
        }
        
        /// <remarks/>
        public string tripod_manifacturer {
            get {
                return this.tripod_manifacturerField;
            }
            set {
                this.tripod_manifacturerField = value;
            }
        }
        
        /// <remarks/>
        public photo_tech_storeTripodTripod_price tripod_price {
            get {
                return this.tripod_priceField;
            }
            set {
                this.tripod_priceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class photo_tech_storeTripodTripod_price {
        
        private string currencyField;
        
        private float valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public float Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
            }
        }
    }
}
